<?php

/**
 * @file
 * Open Y Node Alert module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_node().
 */
function openy_node_alert_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    [$sendAlerts, $alerts] = \Drupal::service('openy_node_alert.alert_manager')->getAlerts($node);
    if ($sendAlerts) {
      $variables['#attached']['library'][] = 'openy_node_alert/alert';
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function openy_node_alert_entity_presave(EntityInterface $entity) {

  // Check that we are saving Alert node.
  if (
    ($entity->getEntityTypeId() == 'node')
    && ($entity->bundle() == 'alert')
  ) {

    if (
      $entity->hasField('field_alert_visibility_pages')
      && !$entity->get('field_alert_visibility_pages')->isEmpty()
    ) {

      // Trim any leading or trailing spaces as they can cause false positives.
      $visibility_paths = trim($entity->get('field_alert_visibility_pages')->value);
      $entity->field_alert_visibility_pages->value = $visibility_paths;

      // Convert path to lowercase. This allows comparison of the same path.
      // with different case. Ex: /Page, /page, /PAGE.
      $visibility_paths = mb_strtolower($visibility_paths);
      $pages = preg_split("(\r\n?|\n)", $visibility_paths);

      $path_matcher = \Drupal::service('path_alias.manager');
      $cacheTags = [];
      foreach ($pages as $page) {
        $canonical_path = $path_matcher->getPathByAlias($page);
        // Check if this path is a node path.
        if (strpos($canonical_path, 'node') !== FALSE) {
          $nid = explode('/', $canonical_path)[2];
          $cacheTags[] = 'node:' . $nid;
        }
      }
    }

    // Collecting nodes from the Reference field.
    if (
      $entity->hasField('field_alert_belongs')
      && !$entity->get('field_alert_belongs')->isEmpty()
    ) {
      $references = $entity->get('field_alert_belongs')->getValue();
      foreach ($references as $reference) {
        // Reference field is referenced to nodes, using this node tag.
        $cacheTags[] = 'node:' . $reference['target_id'];
      }
    }

    if (!empty($cacheTags)) {
      Cache::invalidateTags($cacheTags);
    }
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_node_alert_form_node_alert_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Show these fields only for the classic style option.
  $form['field_alert_color']['widget']['#states'] = [
    'visible' => [
      ':input[name="field_alert_style"]' => ['value' => 'classic'],
    ],
  ];

  $form['field_alert_text_color']['widget']['#states'] = [
    'visible' => [
      ':input[name="field_alert_style"]' => ['value' => 'classic'],
    ],
  ];

  $form['field_alert_icon_color']['widget']['#states'] = [
    'visible' => [
      ':input[name="field_alert_style"]' => ['value' => 'classic'],
    ],
  ];
}
